removed local composition and added added lamdas for navigation
Chandbaba131/RickAndMorty pull request #10
Opened 2024-11-12 16:05 UTC by Chandbaba131

2024-11-13 06:33 UTC, shubhamsinghmutualmobile requested changes

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on gradle/libs.versions.toml
> +robolectric = "4.10"
Consider removing this if you're not using robolectric in your tests

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on gradle/libs.versions.toml
> +robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
Same

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/HomeScreen.kt
> +    onNavigate: (String) -> Unit
Use more descriptive names for your variables and params. For example `onNavigateToCharacterDetailScreen` in this case.

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/HomeScreen.kt
> +            AllCharacters(allCharacters,innerPadding,onNavigate)
Try using named parameters to make your code easier to read. If you can't remember it yourself, then use a lint tool to help yourself, like KtLint, or some other.

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/characters/AllCharacters.kt
> +    onNavigate: (String) -> Unit
Same, rename it to something more descriptive

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/characters/AllCharacters.kt
> +    innerPadding: PaddingValues,
Composables should rather accept a `Modifier` rather than direct values like `Padding`, `Margin`, `Color`, etc.

A composable should generally only ask for very specific logic-related states, essentially the ones that it really requires to draw itself, and any non-logic related states might be passed via a Modifier.

For example the `innerPadding` has very little to do with how this composable will work. It mainly depends on the `UiState`. So, it should only ask for the `UiState` value as a param, and other common things like `padding`, `color`, `offset`, etc can be delegated to a Modifier.

Try to follow this approach with all your composables. They should delegate as much as they can to their parent composables and only ask for logic-related states as their params.

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/characters/CharacterListItem.kt
> +    onNavigate : (String) -> Unit,
Same, rename it to be more descriptive

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/characters/CharacterListView.kt
> +    onNavigate: (String) -> Unit
Same, delegate padding to `Modifier`, and rename `onNavigate`

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/characters/CharacterListView.kt
> +            CharactersListItem(onNavigate,item)
Use named params

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/characters/CharacterListItem.kt
> +                    onNavigate(NavigationRoutes.CharacterDetails.createRoute(item?.character?.id?:""))
This composable should not be responsible for deciding which screen to navigate to. It should only be responsible for providing the `id` of the character that the user clicks on. Navigation should be the responsibility of one of its parent Composables. Ideally, it should be done inside `NavigationController.kt` and all its child composables should just pass the character `id` up, until it reaches that file.

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/navigation/NavigationController.kt
> +            characterId.orEmpty().let { viewModel.getCharacterDetails(it) }
Is it possible for us to get character details for blank id? If not, then consider removing `orEmpty` here.

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/navigation/NavigationController.kt
> +            HomeScreen(viewModel.charactersState, topBarTitle, navigate)
Consider using named params

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/main/java/com/example/presentation/navigation/NavigationController.kt
> +            homeViewModel.updateAppBarTitle(stringResource(R.string.app_name))
ViewModel should not be responsible for performing UI-related tasks 🤔 Updating App Bar title should be the job of this Composable only.

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +        every { Log.isLoggable(any(), any()) } returns false
Why do we need this code?

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
>      fun testFetchCharacterUpdatesToUi() =
Try naming your tests in a `given_when_then` format if your test names are not straightforward enough.

2024-11-13 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +                val expectedCharacters = differ.snapshot().items
What exactly are we testing here? Seems like we're just testing the `differ` object with different values here 🤔

2024-11-14 07:02 UTC, Chandbaba131 commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +        every { Log.isLoggable(any(), any()) } returns false
Since here we are using Differ to compare the expected data and actual data 
so the AsyncPagingDataDiffer is internally using Logs but in the test we had not mocked any logs so i got an error saying that log is not mocked so i added this piece of code so that whenever the Log from differ is executed it will return false

2024-11-14 07:19 UTC, Chandbaba131 commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +                val expectedCharacters = differ.snapshot().items
Here actually we are getting Paging data so i was using differ and taking the snapshot of items 
and comparing both expected and actual items

2024-11-18 05:26 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +        every { Log.isLoggable(any(), any()) } returns false
I don't understand, is `Log` a part of your mocked `CharacterUseCase` or `CharactersViewModel`? Because these are the only 2 entities I see in this test.

2024-11-18 05:30 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +                val expectedCharacters = differ.snapshot().items
I'm not able to understand why we need to use `AsyncPagingDataDiffer` for that. What is our goal here? Isn't it just to compare 2 lists? Can't we do that directly?

2024-11-18 05:33 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +    fun givenValidCharacters_whenInvokeIsCalledInUseCase_thenEmitsMockedPagingDataToStateFlow() =
Using terms like `mocked` is not preferred in test names. The test name should only be concerned with the functionality it wants to test. In this case, it's just being able to emit some data to the state flow regardless of whether it's mocked, faked, or real.

2024-11-18 05:58 UTC, Chandbaba131 commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +                val expectedCharacters = differ.snapshot().items
Here actually i have to compare paging data since i don't have any other option to compare paging data 
so i had used Differ to get the individual items from pager and  differ.snapshot().items is giving me the items from pager so i am comparing those 2 things

2024-11-19 03:55 UTC, Chandbaba131 commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +                assertThat(actualCharacters.size).isEqualTo(expectedCharacters.size)
if we do so it is just comparing the object references instead of paging list 
so i am checking whether both the list size is same or not

2024-11-19 06:33 UTC, shubhamsinghmutualmobile commented on presentation/src/test/java/com/example/presentation/characters/CharactersViewModelTest.kt
> +                assertThat(actualCharacters.size).isEqualTo(expectedCharacters.size)
Okay, if you feel it's reliable, then you can move forward and merge this PR

2024-11-19 06:33 UTC, shubhamsinghmutualmobile approved these changes

2024-11-19 06:44 UTC, merged