setup the dagger
Chandbaba131/RickAndMorty pull request #2
Opened 2024-10-23 06:38 UTC by Chandbaba131

2024-10-23 09:05 UTC, shubhamsinghmutualmobile requested changes
Consider using Hilt instead of Dagger2, get rid of the `NetworkResponse` class and simplify the `UIState` class by writing it as follows:

```kotlin
sealed class UIState<out T> {
    data object Empty : Result<Nothing>()
    data object Loading : Result<Nothing>()
    data class Success<T>(val data: T) : Result<T>()
    data class Error(val exception: Exception) : Result<Nothing>()
}
```

2024-10-23 09:05 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/characters/AllCharacters.kt
> +    val viewModelFactory = context.appComponent.viewModelFactory()
Hilt was good. It has Compose extensions like `hiltViewModel()`. Consider replacing `Dagger2` with `Dagger-Hilt`.

2024-10-23 09:05 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/characters/AllCharacters.kt
> +        ).get(CharactersViewModel::class.java)
This is not being `remember`ed as well 🤔

2024-10-23 09:05 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/domain/repository/usecase/CharacterUseCase.kt
> +            }
No need for the `NetworkResult` class here. It's not providing anything useful. Just make the function `suspend`ed and handle `Empty`, `Loading`, `Success`, and `Error` cases within the ViewModel only.

2024-10-23 10:35 UTC, shreyansh-mm commented
In future please try to make PRs as small as possible, plus this PR contains some formatting change which are not supposed to be part of this PR.

Let's try to make cleaner and smaller PRs. Where the PR has exactly the work which the title & description says.

2024-10-24 07:47 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/data/di/module/CharactersProvider.kt
>  class CharactersProvider {
Rename this to `CharactersModule` to keep the naming consistent

2024-10-24 07:56 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/characters/AllCharacters.kt
> +    }
Probably write `.value` with the variable declaration itself to avoid having to force cast it to `UiState.Success`. For example:

```kotlin
val uistate by viewModel.charactersState.collectAsState()
// or val uistate = viewModel.charactersState.collectAsState().value is also okay
     when (uistate) {
         is UiState.Empty -> {}
         is UiState.Error -> {}
         is UiState.Loading -> {
             CircularProgressIndicator(modifier = Modifier.height(100.dp).width(100.dp))
         }
         is UiState.Success -> {
             val lazyPagingItems = uistate.data.collectAsLazyPagingItems()
             val charactersList = remember { lazyPagingItems }
             CharactersList(charactersList)
         }
     }
```

2024-10-24 07:56 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/uistate/UiState.kt
> +}
It's probably best to make UIState a generic class so that it can be reused for other responses too.

2024-10-24 07:56 UTC, shubhamsinghmutualmobile commented on settings.gradle.kts
> +        id("org.jmailen.kotlinter") version "4.4.1"
Make this an `alias` entry instead

2024-10-24 07:58 UTC, shubhamsinghmutualmobile commented
Also, please assign this issue to yourself and give it the `Enhancement` label

2024-10-29 04:39 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/CharactersViewModel.kt
> +        val charactersState: StateFlow<UiState<GetCharactersQuery.Result>> get() = _charactersState.asStateFlow()
Either omit the return type `StateFlow<UiState<GetCharactersQuery.Result>>` or omit `.asStateFlow()`. They're both doing the same thing.

2024-10-29 04:40 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/CharactersViewModel.kt
> +                        _charactersState.update { UiState.Success(charactersUseCase.invokeCharacters()) }
The `update()` API is useful when you want to use the existing value of the flow in your calculation. For pure emissions, use `emit()` instead.

2024-10-29 04:47 UTC, shubhamsinghmutualmobile approved these changes

2024-10-29 04:47 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/HomeScreen.kt
> +            NavigationController(navController, innerPadding)
Don't provide it the `innerPadding` value directly. Instead, make the composable ask for a `modifier: Modifier` and write `Modifier.padding(innerPadding)` here.

2024-10-29 04:47 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/RickAndMortyAppBar.kt
>          Text(title, style = TextStyle(fontSize = 16.sp), color = MaterialTheme.colorScheme.onBackground)
Try using a style provided by `MaterialTheme.typography` instead. You should be able to see specifically which one to use on [Figma](https://www.figma.com/design/6YIvNz1CxM8K3QTyyy0TmK/Rick-%26-Morty-App-(Roadmap)?node-id=58795-469).

<img width="1512" alt="Screenshot 2024-10-29 at 10 13 29 AM" src="https://github.com/user-attachments/assets/4354989f-70b9-407a-a485-885d4505be25">

2024-10-29 04:47 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/characters/AllCharacters.kt
> +            CircularProgressIndicator(modifier = Modifier.height(100.dp).width(100.dp))
Use `Modifier.size(100.dp)` instead

2024-10-29 04:47 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/characters/AllCharacters.kt
> +            val lazyPagingItems = (uistate).data.collectAsLazyPagingItems()
Remove unnecessary parentheses `()` and rewrite it as:
`val lazyPagingItems = uistate.data.collectAsLazyPagingItems()`

2024-10-29 04:47 UTC, shubhamsinghmutualmobile commented on app/src/main/java/com/example/rickandmorty/presentation/characters/AllCharacters.kt
> +            val charactersList = remember { lazyPagingItems }
No need to `remember` this value because `collectAsLazyPagingItems` is taking care of that for us

2024-10-29 05:33 UTC, merged